### PR TITLE
Include features and ifixes in SBoM

### LINKED ISSUE #137: Include iFixes & Features with SBOM information
## What happened?

* What were you attempting to do?
When building an app, the buildpack generates SBOM information. This does not presently include information about applied iFixes or additional Features that have been installed.

* What did you expect to happen?

Add some indication that iFixes have been applied and that Features have been installed as this can impact whether a generated image is vulnerable to security issues.

It is unclear exactly how this information would need to be represented in the SBOM metadata such that security scanners like [Grype](https://github.com/anchore/grype/) are able to report on the information in a meaningful way. More investigation needs to be done before changes an be made.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by hibell**
## Summary
Fixes #137.

This change scans the base and distribution layers to include dependencies in the SBoM. I could not figure out a more targeted approach since there is no way to query the Liberty feature installer tool to see which jars and versions it installs for a given feature at the moment.

I also tried investigating on providing the information in a manner useful to vulnerability scanners like grype but it did not look possible since Liberty only includes the version of Liberty that a vulnerability is resolved in and does not include the which feature is vulnerable and what version of the feature it is resolved in. I talked with the lead maintainer for Open Liberty and he was open to improving this process.

I was not sure the best approach for including feature and iFix information in the SBoM. If there is a better approach to include useful information, please let me know and I can try to update.

## Use Cases
* Include feature and iFix information in the SBoM.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by dmikusa** [comment]
@hibell Can you resolve this merge conflict? Looks straightforward. I can perhaps take a look through tonight or tomorrow. Thanks

**Comment by hibell** [comment]
@dmikusa OK. It should be good now. Thanks.

**Comment by dmikusa** [comment]
:( sorry looks like there are still conflicts.

**Comment by hibell** [comment]
Ah, yeah. It looks like Liberty versions were updated yesterday and were conflicting with the `buildpack.toml` updates to give Open Liberty its own CPE. It should be good again. Thanks.

**Comment by dmikusa** [comment]
I'm not sure this is exactly what we want. While `syft` does a nice job scanning a JAR/WAR or Java application, it doesn't really do a good job scanning a server like Liberty. It doesn't see Liberty as a whole and, in my experience, reports on whatever JAR files Liberty happens to include because it basically treats Liberty as a Java app, not Liberty specifically.

I like storing the information on the appropriate layers, that seems reasonable and it should make it visible. The trouble is that we already get dependency information for [Liberty for free, libpak handles that](https://github.com/paketo-buildpacks/libpak/blob/main/layer.go#L234-L239), but there's not really a way presently to append to that. It would be nice to append additional information for the features and iFixes, but the question is how.

We could...
- ignore what's written, generate a new set of info for Liberty + iFixes, and write that out
- try to read what's written, append to it and write it back out
- try to pass in additional artifacts to libpak somehow so it can write them all out

The first one sounds the most reasonable. It's a bit of extra work, but I worry about trying to read in the Syft format and losing data, there's also no code to read it in at the moment, so that would be a new addition. I'm also fairly certain we can't modify the libpak API without breaking changes, and that's not something we can really do now (although if you have suggestions I'd be interested), down the road we should definitely include a way to do this.

Anyway, to accomplish the first option, I think you'd basically have to copy [this](https://github.com/paketo-buildpacks/libpak/blob/main/layer.go#L234-L239) into your layer contributor, at the end. Then create more artifact objects, one for each of the iFixes and features, including those in the list, and write it all out.

At least by doing this, the feature names & iFixes information can be put into the SBOM metadata.

I'm not sure that tools like `grype` would be able to understand it but a human looking at the information should be able to see that features & ifixes are included and that seems like a good first step to me.

Reach out on Slack or here if you want to talk through it more. This is the first time we've had to work through this, where there can be different variations of the dependency, so we don't have an establish pattern for how to handle this.

**Comment by hibell** [comment]
@dmikusa I attempted to make the changes you recommended. Let me know if more changes are needed. Thanks!

**Comment by kevin-ortega** [comment]
@dmikusa Can you please review Hank's latest changes?

**Comment by dmikusa** [comment]
I took a quick look and it looks good. I need to do some testing still, and I need to find some time for that. I'll try to get it done by the end of the week for you.

**Review by dmikusa — APPROVED** [review]

**Comment by dmikusa** [comment]
I did some test builds and was able to get the SBOM from the generated images. Looks good to me.

**Pull request merged**
